use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::market::{Direction, SecurityId};
use crate::timeframe::Timeframe;

/// Type of trading signal based on Brooks PA methodology
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SignalType {
    /// Entry in the direction of the prevailing trend after a pullback
    TrendContinuation,
    /// Reversal trade at the end of a trend
    TrendReversal,
    /// Entry on a breakout of a key level
    BreakoutEntry,
    /// Entry after a breakout fails and reverses
    FailedBreakoutEntry,
    /// Entry on a pullback within a trend
    PullbackEntry,
    /// Entry on a breakout from a trading range
    TradingRangeBreakout,
    /// Quick scalp in the direction of the trend
    WithTrendScalp,
    /// Counter-trend swing trade (higher risk)
    CounterTrendSwing,
}

/// Higher-timeframe context attached to a signal
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SignalContext {
    /// Higher-timeframe trend direction
    pub htf_trend_direction: Option<Direction>,
    /// Whether the signal aligns with the higher timeframe
    pub htf_aligned: bool,
    /// Key support/resistance levels from higher timeframe
    pub htf_key_levels: Vec<Decimal>,
    /// Description of the setup context
    pub description: String,
}

/// A trading signal generated by the strategy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    pub id: Uuid,
    pub timestamp: DateTime<Utc>,
    pub security: SecurityId,
    pub direction: Direction,
    pub signal_type: SignalType,
    pub entry_price: Decimal,
    pub stop_price: Decimal,
    pub target_price: Option<Decimal>,
    /// Confidence score from 0.0 to 1.0
    pub confidence: f64,
    pub timeframe: Timeframe,
    pub context: SignalContext,
}

impl Signal {
    /// Risk per unit (distance from entry to stop)
    pub fn risk_per_unit(&self) -> Decimal {
        (self.entry_price - self.stop_price).abs()
    }

    /// Reward-to-risk ratio, if a target is set
    pub fn reward_risk_ratio(&self) -> Option<Decimal> {
        self.target_price.map(|target| {
            let risk = self.risk_per_unit();
            if risk.is_zero() {
                return Decimal::ZERO;
            }
            (target - self.entry_price).abs() / risk
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::market::Exchange;
    use rust_decimal_macros::dec;

    fn make_signal() -> Signal {
        Signal {
            id: Uuid::new_v4(),
            timestamp: Utc::now(),
            security: SecurityId::etf("510050", Exchange::SH),
            direction: Direction::Long,
            signal_type: SignalType::PullbackEntry,
            entry_price: dec!(3.100),
            stop_price: dec!(3.050),
            target_price: Some(dec!(3.200)),
            confidence: 0.75,
            timeframe: Timeframe::Minute5,
            context: SignalContext::default(),
        }
    }

    #[test]
    fn test_risk_per_unit() {
        let signal = make_signal();
        assert_eq!(signal.risk_per_unit(), dec!(0.050));
    }

    #[test]
    fn test_reward_risk_ratio() {
        let signal = make_signal();
        let rr = signal.reward_risk_ratio().unwrap();
        assert_eq!(rr, dec!(2.0)); // (3.200 - 3.100) / (3.100 - 3.050) = 0.1 / 0.05 = 2.0
    }

    #[test]
    fn test_no_target() {
        let mut signal = make_signal();
        signal.target_price = None;
        assert!(signal.reward_risk_ratio().is_none());
    }
}
